### ISSUE TITLE
undefined symbol: make_scrambled_password

### ISSUE THREAD

**Issue by own3mall** [NigelCunningham/pam-MySQL#14]
Any chance you know how to fix the "undefined symbol: make_scrambled_password" error with newer versions of mysql / mariadb that no longer export this?

https://bugs.launchpad.net/ubuntu/+source/pam-mysql/+bug/1574900?comments=all

You can see it no longer work in Ubuntu 16.04 any flavor in Virtualbox.  If I knew how to fix it, I would.  Please help?  This module is too important to die.  There is no replacement for it.

**Comment by stewjohn** [comment]
@own3mall 

I opened a PR for this but in case it isn't merged you can see https://github.com/stewjohn/pam-MySQL-1

**Comment by NigelCunningham** [comment]
Merged today, thanks.
