### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by wferi** [NigelCunningham/pam-MySQL#19]
Hi,

(Moving this out of the closed pull request to gain more visibility.)

Have you got any plans about making a release? It would be nice if you met the Debian stretch freeze: we could then ship a proper release in stretch instead of some Git snapshot.
Probably there are some outstanding issues which would be worth fixing, but having an official 0.8 would make it easier to see what's left to do and at the same time gain some extra exposure and testing.
So if there aren't any serious show-stopper bugs in the current code, I ask you to release it as soon as possible, then refine it in further releases. If you don't feel like making a release, please tell, and also whether you object against me packaging some Git snapshot instead for Debian.

Regards,
Feri.

**Comment by NigelCunningham** [comment]
Ah thanks for that. Will tag it now.

**Comment by NigelCunningham** [comment]
Release tagged and pushed. Thanks for all of your help!

**Comment by wferi** [comment]
Thank *you* for adopting this code and taking care for it!
Will you attach a proper `make dist` tarball to the fresh release (if yes, please add a signature as well if you can), or shall I base the package on the archive automatically provided by GitHub? (The distribution tarball created by Automake contains all the Autotools and Libtool files necessary for building the package, so that people building from it needn't have those tools installed.)

**Comment by NigelCunningham** [comment]
Let's go for basing it on the github archive. I have enough on my plate without adding another thing to forget to do at the next release :)

I want to start doing some cleanup but I have a big project I'm in the middle of at the moment so I won't make any promises. I will say though that if you have any patches you want, just open a PR :)

**Comment by wferi** [comment]
New PR opened :)
By the way `configure.ac` has version number 0.8, but you tagged 0.8.0. It's best to keep these version numbers the same to reduce confusion. I uploaded the new package with upstream version number 0.8.0 for now.
