### ISSUE TITLE
Support for sha2 (sha256 / sha512 hashes)

### ISSUE THREAD

**Issue by matthijs** [NigelCunningham/pam-MySQL#23]
Hi,

Is it possible to support sha2 ? (sha256 / sha512 hashes)

We are using hashes that are usually generated by the openssl library, an example of generating such a digest:
```c++
std::string password = "somepassword";

// generate a SHA512 hash using the openssl library
char buf[SHA512_DIGEST_LENGTH];
SHA512_CTX ctx;
if (!SHA512_Init(&ctx)) {
    std::cerr << "failed to initialize." << std::endl;
}
if (!SHA512_Update(&ctx, password.c_str(), password.length())) {
    std::cerr << "failed to update sha context." << std::endl;
}
if (!SHA512_Final((unsigned char *)buf, &ctx)) {
    std::cerr << "failed to get the hash." << std::endl;
}
```

It's not a complete example, but it gives an head start hopefully.

Regards, Matthijs

**Comment by NigelCunningham** [comment]
Yes, it's possible. I'll add support once I get the refactoring I'm currently doing bedded down.

**Comment by NigelCunningham** [comment]
Committed just now. Enjoy!
