### ISSUE TITLE
Wrong SHA1 hash

### ISSUE THREAD

**Issue by eriklundin** [NigelCunningham/pam-MySQL#24]
Hi,

I've tried your module but it looks like its calculating the the hash wrong. I've generated an SHA1 hash from the string "test" which is: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3

Now i've added an extra log output on line 2928 in pam_mysql.c:
syslog(LOG_AUTHPRIV | LOG_ERR, buf);

Which generates the following output when trying to login with the password "test":
Dec 30 22:15:47 host sshd[26898]: 14b9961cd982a22949737f143325c0370ab90dd9

Which is wrong...

**Comment by jeff-kilbride** [comment]
FWIW, i've tested it with the `sha1` function built-in to `mysql` and it works. So:
```
insert into table (id, hash) values ('some_id', sha1('some_clear_password'));
```
and in your config file:
```
users.password_crypt = 4
```
This works for me.

**Comment by NigelCunningham** [comment]
Hi.

I've just tested with the tip of the current 0.8.x branch and the current hash is produced there and the password is accepted.

**Comment by NigelCunningham** [comment]
Closing in preparation for a 0.8.1 release.
