### ISSUE TITLE
undefined symbol: SHA1xxx

### ISSUE THREAD

**Issue by Gussoh** [NigelCunningham/pam-MySQL#26]
Hi,

While trying to replace the original mysql pam with this I ended up in a dead end.

If I configure with:
_./configure --with-pam-mods-dir=/lib/security --with-openssl=**no**_
I get:
_PAM unable to dlopen(pam_mysql.so): /lib/security/pam_mysql.so: undefined symbol: **SHA1Final**_

If I configure with:
_./configure --with-pam-mods-dir=/lib/security --with-openssl=**yes**_
I get:
_PAM unable to dlopen(pam_mysql.so): /lib/security/pam_mysql.so: undefined symbol: **SHA1Init**_

I don't even want to use SHA1. But it doesn't seem to help with "crypt=plain" in the pam config

Doing this on Ubuntu 16.04 with the standard packages for mysql and everything.

Please tell me if I can help with providing more information. I just want it to work as soon as possible :)

**Comment by Gussoh** [comment]
I tried the last stable, v0.8.0, and that seems to be working! So this problem started recently.

**Comment by NigelCunningham** [comment]
Thanks for the report.

I have a fix coming in the 0.8.1 release, out soon. If you have time, would you please check out the v0.8.x branch and confirm it works okay for you?

Nigel

**Comment by basvdburg** [comment]
Hello Nigel,

I encountered the same problem on my CentOS 7 installation.

saslauthd: PAM unable to dlopen(/usr/lib64/security/pam_mysql.so): /usr/lib64/security/pam_mysql.so: undefined symbol: SHA1Init

The module in the v0.8.x branch is working for me!

**Comment by NigelCunningham** [comment]
Thanks!

**Comment by NigelCunningham** [comment]
Closing in preparation for doing a 0.8.1 release.
