### ISSUE TITLE
undefined symbol: pam_set_data

### ISSUE THREAD

**Issue by Gussoh** [NigelCunningham/pam-MySQL#27]
When using the latest stable, v0.8.0, I get 
_PAM unable to dlopen(pam_mysql.so): /lib/security/pam_mysql.so: undefined symbol: pam_set_data_
when trying to authenticate the openvpn connection.

I noticed a commit, "Link the module with the PAM library", commit 6d5d20bfd2dd15662..
I used this commit instead of latest stable and now it is working.

To summarise I cant use the latest commit since I get undefined symbols for SHA1Init or SHA1Final (previous issue I submitted), and I cant use the latest stable since I get undefined symbol: pam_set_data.

Thank you very much for the very good commit message! I would never have found this otherwise! :)

**Comment by NigelCunningham** [comment]
Thanks for the report. Credit goes to @wferi for the message.

I'll look into creating an alternative solution or just reverting that commit.

**Comment by wferi** [comment]
I can take credit for the commit message, but not for the fix itself, which originates from [Christian Hammers](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=418500#50) (I neglected doing the research before). But honestly, I still don't understand precisely why pam_mysql works with some applications regardless.

**Comment by NigelCunningham** [comment]
A new release will be out soon, including this fix. I'll close this bug.
