### ISSUE TITLE
Debian/Jessie error: possibly undefined macro: AC_MSG_ERROR

### ISSUE THREAD

**Issue by dragoscirjan** [NigelCunningham/pam-MySQL#28]
Hello, tried to compile the module under Debian Jessie. See compiling commands and error bellow.

Probably forgot to install something, still I need your help on it.

```
apt-get install -y autoconf automake build-essential libmysqlclient-dev libpam-dev libssl-dev
autoreconf -f -i
```

```
configure.ac:26: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:45: error: possibly undefined macro: AS_IF
configure.ac:47: error: possibly undefined macro: AC_DEFINE
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by Promaethius** [comment]
You'll need a few extra packages:
`apt-get install -y autoconf automake build-essential libmysqlclient-dev libpam-dev libssl-dev libtool pkg-config`

Now run these commands in order in the build directory:
```
libtoolize
aclocal
autoheader
autoreconf -f -i
```

**Comment by NigelCunningham** [comment]
Hi @dragoscirjan.

Did the instructions from @Promaethius cover everything you needed?

Regards,

Nigel

**Comment by dragoscirjan** [comment]
Hello @NigelCunningham , @Promaethius ,
Thank you for you answer. I am currently involved in something else (and also will be in vacation for the next weeks) I think I remember compiling the tool once but I'm not sure. If you need to close the issue please do. I have the info saved already and will use it pretty soon.

**Comment by NigelCunningham** [comment]
Ok; thanks!

**Comment by jeff-kilbride** [comment]
FYI, these instructions worked great! You might consider adding them to the beginning of the INSTALL.pam-mysql file, for people who are less familiar with all the necessary tooling. I got stuck on failing to install the `libtool` and `pkg-config` packages the first time around.

**Comment by Promaethius** [comment]
@NigelCunningham Thanks!

**Comment by zbuttram** [comment]
Just wanted to add a quick note here, looks like the additional instructions for necessary packages were removed from the installation instructions at some point. Just ran into this problem myself and had to find this issue.
