### ISSUE TITLE
Default value for md5 config is wrong

### ISSUE THREAD

**Issue by flippy84** [NigelCunningham/pam-MySQL#40]
When setting crypt to 1 in the config and commenting out the md5 option it still uses md5 for hashing even if the default is supposed to be disabled.

Probable fix would be to set `ctx->md5` to 0 instead of -1 in `pam_mysql_init_ctx`.

**Comment by NigelCunningham** [comment]
Thanks for pointing that out. Pull request https://github.com/NigelCunningham/pam-MySQL/pull/45 includes that change and I'm intending to merge that once a small whitespace issue is fixed.

Apologies for the slow response.

**Comment by NigelCunningham** [comment]
Referenced patch has been applied; closing this one now.
