### ISSUE TITLE
Time to roll v0.8.2?

### ISSUE THREAD

**Issue by CRCinAU** [NigelCunningham/pam-MySQL#56]
It seems most distros will only send out new versions once an official release is made.

Currently, from my testing of pam_mysql now - 0.8.1 only seems to support md5(?) via crypt. From the commit history, I believe using crypt will now also do up to sha512.

It would be good to release this (if working) as v0.8.2 so this improvement can be put out in the distros.

**Comment by thundur** [comment]
+1

**Comment by mxftw** [comment]
+1

Steven Haigh <notifications@github.com> schrieb am Di., 14. Mai 2019, 03:42:

**Comment by NigelCunningham** [comment]
I'm currently working on switching the build system to meson (I find autotools incomprehensible!). Once I get that going, I'll do a new release. Apologies for the delay.

**Comment by NigelCunningham** [comment]
Now fixed (1.0 pre-releases are available for testing; I've successfully built and tested on Arch Linux, Mint and Centos 8 so far).
