### ISSUE TITLE
Dont erro log, and dont login with pam-mysql

### ISSUE THREAD

**Issue by ph1823** [NigelCunningham/pam-MySQL#63]
Hello, sorry to disturb you for something that may be stupid. 
But there, I made a vsftpd server, with an old version of pam, I just updated on yours, and it does not work anymore. So I activated the verbose option, to have more log but here is what it gives me (in /var/log/secure, i dont find /var/log/auth*):
```
Apr  8 23:46:54 datahosting vsftpd[9528]: pam_unix(vsftpd:auth): check pass; user unknown
Apr  8 23:46:54 datahosting vsftpd[9528]: pam_unix(vsftpd:auth): authentication failure; logname= uid=0 euid=0 tty=ftp ruser=datahosting_minecraft rhost=my_private_host
```

Here is my configuration pam:

```
#%PAM-1.0
auth sufficient /usr/lib64/security/pam_mysql.so user=datahosting passwd=my_secret_password  host=localhost db=datahosting table=ftp_accounts usercolumn=username   passwdcolumn=pass crypt=9 verbose=1
account sufficient /usr/lib64/security/pam_mysql.so user=datahosting passwd=my_secret_password  host=localhost db=datahosting table=ftp_accounts usercolumn=username  passwdcolumn=pass crypt=9 verbose=1
auth        sufficient     pam_unix.so try_first_pass nullok
account     sufficient       pam_unix.so
session    required     pam_loginuid.so
```

I may not be looking for the right logs.
Is the log file in /var/log ?

I am sincerely sorry to disturb you for this banal thing, which surely comes from me. But it's annoying that my vsftpd server is no longer working, so I would like to resolve this problem.

I am running on Centos 8.

Thank for your reply.

**Comment by ph1823** [comment]
It's good, I managed to get the logs. Sorry to disturb you.

I still have a little problem, the logs give me this:
```
Apr  9 11:13:58 datahosting vsftpd[23271]: pam_mysql - pam_sm_authenticate() returning 3.
```

does this mean that pam mysql cannot connect to the server?

**Comment by ph1823** [comment]
Still sorry to have disturbed you, it came from my installation of pam_mysq, I had not configured the mysql well

**Comment by NigelCunningham** [comment]
Ok. Glad you managed to get logs. I think I could improve the logging there and will work on that.

Thanks!
