### ISSUE TITLE
something went wrong when invoking crypt() - No such file or directory

### ISSUE THREAD

**Issue by PanzerKunst** [NigelCunningham/pam-MySQL#7]
Hi Nigel,

I'm having an error when using pam-MySQL.
When I run the following command: `sudo testsaslauthd -u 'the_username' -p 'the_password' -s smtp`, I get the follwing error printed to `/var/log/auth.log`: `saslauthd[21550]: pam_mysql - something went wrong when invoking crypt() - No such file or directory`. The result of `testsaslauthd` is `0: OK "Success."` though.

Any idea on how to get rid of this error?

Cheers,
Christophe

**Comment by NigelCunningham** [comment]
Sorry for taking so long to reply. Is this still an issue I need to look into?

**Comment by StraToN** [comment]
Hello, sorry I can't tell if the issue is still there. I reinstalled the server from scratch some time ago and did not set any pam-mysql.

**Comment by PanzerKunst** [comment]
It's been too long ago. So I think it's best to close the issue.
