### ISSUE TITLE
undefined symbol: MD5

### ISSUE THREAD

**Issue by drzraf** [NigelCunningham/pam-MySQL#8]
I've the following issue using the drupal7 pam-mysql module (dovecot consumer):
`auth worker: PASSV: PAM unable to dlopen(pam_mysql.so): /lib/security/pam_mysql.so: undefined symbol: MD5`

It _could_ be related to the squeeze -> wheezy upgrade.

Using
libssl0.9.8 (0.9.8o-4squeeze14)
libssl1.0.0:amd64 (1.0.1e-2)
openssl (1.0.1e-2)
libc6 (2.13-38)

`./configure; make`
`# nm .libs/pam_mysql.so |grep MD5
                 U MD5`

**Comment by NigelCunningham** [comment]
Thanks. Added in 1fe94c550df74e33.
