### ISSUE TITLE
pam_MySQL is only querying the database if the username has a login account.

### ISSUE THREAD

**Issue by rjensen-466** [NigelCunningham/pam-MySQL#85]
I am having a hard time getting pam_MySQL to work completely for me. I am using cyrus-sasl2 with MECH pam. If I run the command **saslautd -u robert -p secret -s imap** (a valid login account on my machine,) pam_MySQL will query the database. If I enter the command **saslauthd -u robert -r mydomain.com -p secret -s imap** no query is performed and the entry in /var/log/secure is 'pam_mysql - required option "user" is not set.'
Any ideas on what I can check or am doing wrong?

**Comment by NigelCunningham** [comment]
Sorry for the slow reply - for some reason I never received an email notification of your issue.

I don't have saslauthd installed locally so I can't try things myself, sorry. What I would suggest is adding verbose debugging options to your PAM config - that should provide you with more insight into what's going on.

I hope that helps!
